"""empty message

Revision ID: 18a79280ebf1
Revises: dc816b92e3f
Create Date: 2015-01-18 01:28:05.645000

"""

# revision identifiers, used by Alembic.
revision = '18a79280ebf1'
down_revision = 'dc816b92e3f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_project_comment', sa.Column('modified', sa.Boolean(), nullable=True))
    op.add_column('type_project_comment', sa.Column('modified_time', sa.DateTime(), nullable=True))
    op.add_column('type_work', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('type_work', 'cretion_time')
    op.add_column('type_work_comment', sa.Column('modified', sa.Boolean(), nullable=True))
    op.add_column('type_work_comment', sa.Column('modified_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_work_comment', 'modified_time')
    op.drop_column('type_work_comment', 'modified')
    op.add_column('type_work', sa.Column('cretion_time', mysql.DATETIME(), nullable=True))
    op.drop_column('type_work', 'date')
    op.drop_column('type_project_comment', 'modified_time')
    op.drop_column('type_project_comment', 'modified')
    ### end Alembic commands ###
