"""empty message

Revision ID: 1a9cfdbd85e0
Revises: 4da8f5fd4a42
Create Date: 2015-01-21 18:04:41.476000

"""

# revision identifiers, used by Alembic.
revision = '1a9cfdbd85e0'
down_revision = '4da8f5fd4a42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
