"""empty message

Revision ID: 1b219f87ed60
Revises: 2b759ff46b1c
Create Date: 2015-02-07 14:35:54.903000

"""

# revision identifiers, used by Alembic.
revision = '1b219f87ed60'
down_revision = '2b759ff46b1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_project', sa.Column('category', sa.Enum('READING', 'DISPLAYING', 'LETTERING'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_project', 'category')
    ### end Alembic commands ###
