"""empty message

Revision ID: 232f6f422375
Revises: 53161ffa6944
Create Date: 2015-02-07 14:25:30.388000

"""

# revision identifiers, used by Alembic.
revision = '232f6f422375'
down_revision = '53161ffa6944'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
