"""empty message

Revision ID: 3d430a5387fe
Revises: 18a79280ebf1
Create Date: 2015-01-20 18:45:48.889000

"""

# revision identifiers, used by Alembic.
revision = '3d430a5387fe'
down_revision = '18a79280ebf1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_project_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('liker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liker_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['type_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_work_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('liker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liker_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['type_work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'type_work', sa.Column('author_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'type_work', 'author_id')
    op.drop_table('type_work_like')
    op.drop_table('type_project_like')
    ### end Alembic commands ###
