"""empty message

Revision ID: 4431fd412471
Revises: None
Create Date: 2015-01-13 14:54:08.610000

"""

# revision identifiers, used by Alembic.
revision = '4431fd412471'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('profile_image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('font_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_image', sa.String(length=100), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('cretion_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('font_repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('font_type', sa.Enum('READING', 'DISPLAYING'), nullable=True),
    sa.Column('font_title_description', sa.Text(), nullable=True),
    sa.Column('font_author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['font_author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_for_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('Work_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Work_id'], ['font_work.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_for_repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['font_repository.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_for_repository')
    op.drop_table('comment_for_work')
    op.drop_table('font_repository')
    op.drop_table('font_work')
    op.drop_table('author')
    ### end Alembic commands ###
