"""empty message

Revision ID: 4da8f5fd4a42
Revises: 3d430a5387fe
Create Date: 2015-01-21 18:02:49.599000

"""

# revision identifiers, used by Alembic.
revision = '4da8f5fd4a42'
down_revision = '3d430a5387fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
