"""empty message

Revision ID: 53161ffa6944
Revises: 1a9cfdbd85e0
Create Date: 2015-01-25 17:08:19.809000

"""

# revision identifiers, used by Alembic.
revision = '53161ffa6944'
down_revision = '1a9cfdbd85e0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('image', sa.String(length=100), nullable=True))
    op.add_column('author', sa.Column('thumbnail', sa.String(length=100), nullable=True))
    op.drop_column('author', 'profile_image')
    op.add_column('type_project', sa.Column('image', sa.String(length=100), nullable=True))
    op.add_column('type_work', sa.Column('thumbnail', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_work', 'thumbnail')
    op.drop_column('type_project', 'image')
    op.add_column('author', sa.Column('profile_image', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('author', 'thumbnail')
    op.drop_column('author', 'image')
    ### end Alembic commands ###
