"""empty message

Revision ID: 560afa165e58
Revises: 232f6f422375
Create Date: 2015-02-07 14:32:57.054000

"""

# revision identifiers, used by Alembic.
revision = '560afa165e58'
down_revision = '232f6f422375'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
