"""empty message

Revision ID: dc816b92e3f
Revises: 31cf77a43622
Create Date: 2015-01-17 22:51:55.822000

"""

# revision identifiers, used by Alembic.
revision = 'dc816b92e3f'
down_revision = '31cf77a43622'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_project', sa.Column('title', sa.String(length=40), nullable=True))
    op.drop_column('type_project', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_project', sa.Column('name', mysql.VARCHAR(length=40), nullable=True))
    op.drop_column('type_project', 'title')
    ### end Alembic commands ###
